"""Add country_name column to Place

Revision ID: 9e2579e83343
Revises: 489e0a38d6bf
Create Date: 2024-07-31 19:42:40.429675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2579e83343'
down_revision = '489e0a38d6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_name', sa.String(length=128), nullable=True, server_default='Unknown'))

    # Remove the server_default and set nullable=False
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.alter_column('country_name', existing_type=sa.String(length=128), nullable=False, server_default=None)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('country_name')

    # ### end Alembic commands ###
